### ISSUE TITLE
这个本地二维码生成器是否支持中文信息

### ISSUE THREAD

**Issue by lingr7** [CLXiao-1029/MyQRCode#1]
我尝试输入中文生成二维码，然后用微信扫一扫，看到的是？？？是否是不支持中文，我尝试关闭UTF8-BOM，发现也没有用。

**Comment by CLXiao-1029** [comment]
将编码的模式切换成 default 即可

**Comment by CLXiao-1029** [comment]
默认的编码模式是 utf-8 切换成 default 后，重新生成二维码即可成功

**Comment by CLXiao-1029** [comment]
> 我尝试输入中文生成二维码，然后用微信扫一扫，看到的是???是否不支持中文，我尝试关闭UTF8-BOM，发现也没有用。

默认的编码模式是 utf-8 切换成 default 后，重新生成二维码即可成功

**Comment by CLXiao-1029** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            默认的编码模式是 utf-8 切换成 default 后，重新生成二维码即可成功
        
    
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年12月26日 20:15
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [CLXiao-1029/MyQRCode] 这个本地二维码生成器是否支持中文信息 (Issue #1)
        
      
    
  
  

我尝试输入中文生成二维码，然后用微信扫一扫，看到的是？？？是否是不支持中文，我尝试关闭UTF8-BOM，发现也没有用。

**Comment by lingr7** [comment]
ok,感谢及时回复，编码的模式选择Default即可使用中文。
